sonar.projectKey=Domoticz-Zigbee
sonar.organization=your_organization_key
sonar.sources=.
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S5527
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S5332
